name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  unit-test:
    name: Unit tests on ubuntu-latest
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Get pub packages
        uses: actions/checkout@v2
      - run: flutter pub get

      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
      - name: Run Flutter unit tests
        run: flutter test
